// priceList.js
const priceList = {
  men: {
    "Men shirt": 20,
    "T-shirt": 20,
    "Pant": 20,
    "Jeans pant": 20,
    "Silk shirt": 30,
    "Dhoti": 20,
    "Pancha": 20,
    "Pattu pancha": 50,
    "Pipancha": 15,
    "Short": 20,
    "Kurta": 20,
    "Night pant": 20,
    "Men woolen": 30,
    "Coat": 60,
    "Waistcoat": 20,
    "Long coat": 60,
    "Jacket": 60,
    "Hodie": 30,
    "Leather jacket": 100,
    "Sweat shirt": 60,
    "Sweater": 60,
    "Kurta heavy": 30,
    "Safari suit coat": 60,
    "Capri": 20,
    "Sweat pant": 30,
    "Track pant": 30,
    "Swimming dress": 20,
    "Underwears": 15,
  },
  women: {
    "Kurta plane": 20,
    "Salwar plain": 20,
    "Top plane": 20,
    "Dupatta": 10,
    "Legging": 20,
    "Dress bottom": 20,
    "Saree plain": 25,
    "Blouse": 5,
    "Plazo plane": 20,
    "Petticoat": 10,
    "Dress set": 50,
    "Kurta heavy": 60,
    "Salwar very heavy": 40,
    "Plazo very heavy": 40,
    "Dupatta heavy": 30,
    "Pattu saree": 40,
    "Work saree": 60,
    "Blouse heavy": 15,
    "Dress set heavy": 75,
    "Dress set long": 50,
    "Dress set long heavy": 100,
    "Lehenga set plain": 70,
    "Lehenga set heavy": 100,
    "Bridal lehenga set": 200,
    "Bridal lehenga blouse": 50,
    "Skut plain": 20,
    "Skut heavy": 50,
    "Top heavy": 50,
    "Shirt": 20,
    "T-shirt": 20,
    "Pant": 20,
    "Jeans": 20,
    "Capri": 20,
    "Stole": 10,
    "Cort": 50,
    "Jacket": 35,
    "Sweater": 50,
    "Track pant": 20,
    "Scarf": 20,
    "Jumper": 50,
    "Dangre": 20,
    "Slacks": 20,
    "Shall": 20,
    "Long coat": 45,
    "Kudi": 35,
    "Long pullover": 50,
    "Stocking": 10,
    "Groceries": 20,
    "Sweat shirt with hoodi": 35,
    "Nighties": 20,
  },
  kids: {
    "T-shirt": 15,
    "Shirt": 15,
    "Pant": 15,
    "Jeans": 15,
    "Frock": 15,
    "Skirt": 15,
    "Top": 15,
    "Long top": 15,
    "Shorts": 15,
    "Capri": 15,
    "Kurta plane": 15,
    "Salwar plain": 15,
    "Blouse": 15,
    "Dress set plain": 30,
    "Dress set heavy": 50,
    "Dupatta plane": 15,
    "Dupatta heavy": 20,
    "Legging": 15,
    "Frock heavy": 40,
    "Skirt heavy": 40,
    "Sherwani set": 75,
    "Kurta heavy": 30,
    "Salwar heavy": 30,
    "Blouse heavy": 25,
    "Lehenga": 50,
    "Lehenga heavy": 75,
    "Court": 40,
    "Waistcoat": 20,
    "Jacket": 25,
    "Sweater": 30,
    "Track pant": 20,
    "Socks pair": 10,
    "Baby blanket": 30,
  },
  others: {
    "Towels": 20,
    "Blanket": 50,
    "Bed sheet": 30,
    "Pillow covers set": 10,
    "Bathroob": 50,
    "Hand karchief": 10,
    "Muffler": 20,
    "Tie": 10,
    "Uniform set": 50,
    "Sofa covers": 50,
  },
};

export default priceList;
